spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    encode: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000
    security-code-expiration-millis: 50000 #5분
jwt:
  token:
    key: ${JWT_TOKEN_KEY}
  access-expired: 3600000 #1시간  #6000 5초?
  refresh-expired: 86400000   # 1 day
deep-l:
  key: ${DEEPL_KEY}
  host: ${DEEPL_HOST}
telegram-v2:
  url: ${TELEGRAM_URL}
  chatId: ${TELEGRAM_CHAT_ID}
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  redis:
    host: ${LOCAL_REDIS_HOST}
    port: ${LOCAL_REDIS_PORT}

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEVELOPMENT_DB_URL}
    username: ${DEVELOPMENT_DB_USERNAME}
    password: ${DEVELOPMENT_DB_PASSWORD}
  redis:
    host: ${DEVELOPMENT_REDIS_HOST}
    port: ${DEVELOPMENT_REDIS_PORT}

